### ISSUE TITLE
[refactor] Improvement for api fetchers

### ISSUE THREAD

**Issue by Lio-n** [gdsc-gvp/CMS#38]
Implement "**service function for Apis**". 
- These functions encapsulate the details of making the request, handling the response, and  include error handling as well. 

- They abstract away the complexity of working with asynchronous operations like API requests.

E.X:

From this:
```.js
    async function fetchClubData() {
        const response = await fetch("http://localhost:3000/api/getClub/" + clubId);
        const data = await response.json();
        setClubData(data);
    }
 ```
 
to this

 ```.js
    async function fetchClubData() {
        const response = await getClubDataByIdApi(clubId);
        if(response.error){
         	// Handle the error
         	// The error object will contain statusCode:number and data:any.
        }else{
        	setClubData(response.data);
        }
    }
```

The functions could be located at **./src/services/apis**.

**Comment by Lio-n** [comment]
I mean..., I want to work on this. I'm just waiting for an feedback. And then implement it.

**Comment by ramanujangunturu** [comment]
Oh okay

**Comment by Lio-n** [comment]
@himabindu-run  Can i work on this?

**Comment by shanmukh-sai2003** [comment]
@Lio-n  yea you can work on this 🤩

**Comment by Lio-n** [comment]
> @Lio-n yea you can work on this 🤩. Are you going to change every API call or only the above one.

Yes, it will be with all of them.
